import { ReferralSteps } from "components/Chat/ChatComponents/ChatInput/data";
import i18n from "services/localization";
import { MessageType } from "utils/types";
import { IChatMessengerContext } from "./types";

export const chatMessengerDefaultState: IChatMessengerContext = {
  messages: [],
  status: null,
  category: null,
  user: null,
  searchLocations: [],
  requisitions: [],
  locations: [],
  offerJobs: [],
  currentMsgType: null,
  alertCategories: null,
  error: null,
  viewJob: null,
  prefferedJob: null,
  nextMessages: [],
  resumeName: "",
  isChatLoading: false,
  showJobAutocompleteBox: false,
  chooseButtonOption() {},
  dispatch() {},
  setSnapshotMessages() {},
  setCurrentMsgType() {},
  setError() {},
  setViewJob() {},
  submitMessage() {},
  setIsInitialized() {},
  setJobPositions() {},
  setShowJobAutocompleteBox() {},
  setMessages() {},
  isAnonym: true,
  shouldCallAgain: false,
  isCandidateWithEmail: false,
  firebaseToken: null,
  isAuthInFirebase: false,
  setIsAuthInFirebase() {},
  setIsApplyJobSuccessfully() {},
  isApplyJobFlow: false,
  setFlowId() {},
  setSubscriberWorkflowId() {},
  setIsApplyJobFlow() {},
  sendNewMessage: () => Promise.resolve(),
  emailAddress: "",
  firstName: "",
  lastName: "",
  setEmailAddress() {},
  setFirstName() {},
  setLastName() {},
  setSearchLocations() {},
  logout() {},
  createJobAlert() {},
  clearJobFilters() {},
  isChatInputAvailable: false,
  setIsChatInputAvailable() {},
  requisitionsPage: 0,
  setRequisitionsPage() {},
  setIsChatLoading() {},
  setCandidateId() {},
  setIsCandidateAnonym() {},
  setEmployeeId() {},
  isReferralEnabled: false,
  companyName: null,
  setRefBirth() {},
  setRefLastName() {},
  refBirth: "",
  refLastName: "",
  refURL: "",
  chatScreen: null,
  setChatScreen() {},
  employeeLocation: "",
  employeeJobCategory: "",
  setEmployeeJobCategory() {},
  setEmployeeLocation() {},
  searchRequisitions: () => Promise.resolve(null),
  employeeFullName: "",
  setEmployeeFullName() {},
  setUser() {},
  setRequisitions() {},
  setFirebaseToken() {},
  setAlertCategories() {},
  setOfferJobs() {},
  setChatId() {},
  setLocations() {},
  setCategory() {},
  employeeLocationID: "",
  setEmployeeLocationID() {},
  jobSourceID: "",
  employeeJobFamilyNames: [""],
  setEmployeeJobFamilyNames() {},
  referralStep: ReferralSteps.EmployeeId,
  setReferralStep() {},
  hostname: "",
  searchRequisitionsByKeyword: () => Promise.resolve(null),
  searchLocation: () => Promise.resolve(null),
  categoriesForAlert: [],
  languages: [],
  isMultiLanguage: false,
  currentLanguage: "en",
  setCurrentLanguage() {},
  isLiveChat: false,
  setIsLiveChat() {},
  queueId: null,
  setQueueId() {},
  queueChatId: null,
  setQueueChatId() {},
  chatQueueId: null,
  alertTemplateId: undefined,
  setIsCandidateWithEmail() {},
  consentOptIn: null,
  footerPrivacyLink: null,
  inlineDisclaimer: null,
  PPLinkUrl: null,
  chatConsent: false,
  setChatConsent() {},
  withFindJobOption: false,
  isApplyJobSuccessfully: false,
  flowId: undefined,
  subscriberWorkflowId: undefined,
  parentPathname: "",
  isJobSearchLocationMultiSelect: false,
};

const defaultQuestions = (referralCompanyName: string | null) => [
  {
    text: i18n.t("questions:recruitment_process"),
    subType: MessageType.BUTTON,
    isChatMessage: true,
    isOwn: true,
    i18n: "questions:recruitment_process",
  },
  {
    text: i18n.t("questions:part_time"),
    subType: MessageType.BUTTON,
    isChatMessage: true,
    isOwn: true,
  },
  {
    text: i18n.t("questions:flexible_work", {
      companyName: referralCompanyName,
    }),
    subType: MessageType.BUTTON,
    isChatMessage: true,
    isOwn: true,
    i18n: "questions:flexible_work",
    i18nProps: {
      companyName: referralCompanyName,
    },
  },
  {
    text: i18n.t("questions:about_company"),
    subType: MessageType.BUTTON,
    isChatMessage: true,
    isOwn: true,
    i18n: "questions:about_company",
  },
  {
    text: i18n.t("messages:popularQuestions"),
    subType: MessageType.TEXT,
    i18n: "messages:popularQuestions",
  },
];

const newDefaultReferralQuestions = [
  {
    text: i18n.t("questions:get_error_mess"),
    subType: MessageType.BUTTON,
    isChatMessage: true,
    isOwn: true,
    i18n: "questions:get_error_mess",
  },
  {
    text: i18n.t("questions:will_receive_payment"),
    subType: MessageType.BUTTON,
    isChatMessage: true,
    isOwn: true,
    i18n: "questions:will_receive_payment",
  },
  {
    text: i18n.t("questions:how_much_paid"),
    subType: MessageType.BUTTON,
    isChatMessage: true,
    isOwn: true,
    i18n: "questions:how_much_paid",
  },
  {
    text: i18n.t("questions:choose_specific"),
    subType: MessageType.BUTTON,
    isChatMessage: true,
    isOwn: true,
    i18n: "questions:choose_specific",
  },
  {
    text: i18n.t("questions:whats_positions"),
    subType: MessageType.BUTTON,
    isChatMessage: true,
    isOwn: true,
    i18n: "questions:whats_positions",
  },
  {
    text: i18n.t("questions:how_can_refer"),
    subType: MessageType.BUTTON,
    isChatMessage: true,
    isOwn: true,
    i18n: "questions:how_can_refer",
  },
  {
    text: i18n.t("questions:whats_the_requirements_to_refer"),
    subType: MessageType.BUTTON,
    isChatMessage: true,
    isOwn: true,
    i18n: "questions:whats_the_requirements_to_refer",
  },
];

const getReferralMessText = (referralCompanyName: string | null) =>
  i18n.t("questions:refer_friend", { companyName: referralCompanyName });

export const getQuestions = (
  withReferralFlow: boolean,
  referralCompanyName: string | null
) => {
  // if (withReferralFlow && referralCompanyName) {
  //   return [
  //     {
  //       text: getReferralMessText(referralCompanyName),
  //       subType: MessageType.BUTTON,
  //       isChatMessage: true,
  //       isOwn: true,
  //       i18n: "questions:refer_friend",
  //       i18nProps: {
  //         companyName: referralCompanyName,
  //       },
  //     },
  //     ...defaultQuestions(referralCompanyName),
  //   ];
  // }

  if (withReferralFlow) {
    return newDefaultReferralQuestions;
  }

  return defaultQuestions(referralCompanyName);
};
